# Generated by Django 3.2 on 2024-01-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apv', '0002_labourattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourattendance',
            name='attendance_type',
            field=models.CharField(choices=[('REG', 'Regular'), ('OT', 'Overtime'), ('SL', 'Sick Leave'), ('F&F', 'FandF'), ('MR', 'Muster Role')], default='REG', max_length=3),
        ),
    ]
