# Generated by Django 3.2 on 2024-01-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apv', '0003_labourattendance_attendance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourattendance',
            name='posting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labourattendance',
            name='attendance_type',
            field=models.CharField(choices=[('F&F', 'Subcontractor'), ('MR', 'Muster Role')], default='MR', max_length=3),
        ),
    ]
