# Generated by Django 3.2 on 2024-01-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apv', '0004_auto_20240105_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourattendance',
            name='attendance_type',
            field=models.CharField(choices=[('', ''), ('F&F', 'Subcontractor'), ('MR', 'Muster Role')], default='', max_length=3),
        ),
    ]
